package com.example.project.bookmyshowbackend.service.impl;

import com.example.project.bookmyshowbackend.Model.UserEntity;
import com.example.project.bookmyshowbackend.Repository.UserRepository;
import com.example.project.bookmyshowbackend.converter.UserConverter;
import com.example.project.bookmyshowbackend.dto.EntryRequest.UserEntryDto;
import com.example.project.bookmyshowbackend.dto.ResponseDto.UserResponseDto;
import com.example.project.bookmyshowbackend.service.UserService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;


@Service
public class UserServiceImpl implements UserService {

    @Autowired
    UserRepository userRepository;
    @Override
    public void addUser(UserEntryDto userEntryDto) {

        UserEntity userEntity= UserConverter.convertDtoToEntity(userEntryDto);

        userRepository.save(userEntity);
        //id's are automatically generated by @GeneratedValues during save not required in convertDtoToEntity
    }

    @Override
    public UserResponseDto getUser(int id) {
        UserEntity userEntity=userRepository.findById(id).get();//if null it will throw an error or else return value
        // /orElse()
        UserResponseDto userResponseDto=UserConverter.convertEntityToDto(userEntity);
        return userResponseDto;
    }
}
